name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lib/version.rb

permissions: {}

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      packages: write
      attestations: write
    uses: grantbirki/salsa/.github/workflows/ruby.yml@main
    with:
      bootstrap_script: script/bootstrap
      build_script: script/build
      auto_setup_ruby: true
      publish_rubygems: true
      publish_github_packages: true
      push_github_release: true
      sign: true
      verify: true
    secrets:
      RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
